const STORAGE_KEY='profit-engine-scenarios-v2';
function validScenario(s){return s&&['equal','revenue','units'].includes(s.allocation)&&['common','capacity'].every(k=>Number.isFinite(s[k])&&s[k]>=0&&s[k]<=1e9)&&Array.isArray(s.products)&&s.products.length===2&&s.products.every((p,i)=>p.name===['Bags','Shoes'][i]&&typeof p.active==='boolean'&&['price','volume','variable','fixed','avoidable','hours'].every(k=>Number.isFinite(p[k])&&p[k]>=0&&p[k]<=1e9)&&Number.isInteger(p.volume)&&p.avoidable<=100&&p.hours>0);}
let state={current:initial(),proposed:initial()},restoreMessage='';
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const saved=JSON.parse(raw);if(validScenario(saved.current)&&validScenario(saved.proposed)){state=saved;restoreMessage='Your saved numbers have been restored.';}else restoreMessage='Saved numbers could not be restored. The example is shown.';}}catch{restoreMessage='Saving is unavailable in this browser. Keep this page open.';}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('save-status').textContent='Saved in this browser. Your numbers stay after a reload.';}catch{$('save-status').textContent='Could not save. Keep this page open to keep these numbers.';}}
const money=n=>n===null?'Not available':new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:2,minimumFractionDigits:0}).format(n);
const num=n=>new Intl.NumberFormat('en-IE',{maximumFractionDigits:2}).format(n);
const percent=n=>n===null?'No sales':num(n*100)+'%';
const $=id=>document.getElementById(id);
function row(label,key,index,opts={}){return `<div class="input-row"><span>${label}</span>${['current','proposed'].map(side=>{let value=index===null?state[side][key]:state[side].products[index][key];let attrs=`data-side="${side}" data-key="${key}" data-index="${index===null?'company':index}" aria-label="${side} ${index===null?'company':state[side].products[index].name} ${label}"`;if(opts.select)return `<select ${attrs}>${opts.select.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`;if(opts.check)return `<label class="check"><input type="checkbox" ${attrs} ${value?'checked':''}>Sell it</label>`;return `<input type="number" min="${opts.min||0}" max="${opts.max||1000000000}" step="${opts.step||'any'}" value="${value}" ${attrs}>`;}).join('')}</div>`;}
function drawInputs(){
 $('inputs').innerHTML=row('Price per bag · €','price',0)+row('Bags sold','volume',0,{step:1})+row('Cost to make one bag · €','variable',0)+row('Fixed bills per month · €','common',null);
 $('advanced-inputs').innerHTML=state.current.products.map((p,i)=>'<h3 class="product-heading">'+p.name+'</h3>'+row('Sell this product','active',i,{check:true})+(i===1?row('Price per pair · €','price',i)+row('Pairs sold','volume',i,{step:1})+row('Variable cost per pair · €','variable',i):'')+row('Extra fixed costs · €','fixed',i)+row('Fixed costs saved if stopped · %','avoidable',i,{max:100})+row('Machine hours per unit','hours',i,{min:0.01})).join('');
 $('company').innerHTML='<h3>Shared costs & capacity</h3>'+row('Split shared fixed bills by','allocation',null,{select:[['equal','Equal split'],['revenue','Revenue'],['units','Units sold']]})+row('Available machine hours','capacity',null)+'<p class="hint">Extra fixed costs belong to one product. Only the share marked “saved if stopped” disappears when you stop that product. Shared bills stay.</p>';
}
const tableRow=(label,a,b,cls='')=>`<tr class="${cls}"><td>${label}</td><td>${a}</td><td>${b}</td></tr>`;
function render(){const a=calculate(state.current),b=calculate(state.proposed);const delta=b.profit-a.profit;renderLearning(a,b);$('currentProfit').textContent=money(a.profit);$('proposedProfit').textContent=money(b.profit);$('change').textContent=delta===0?'No change':(delta>0?'+':'−')+money(Math.abs(delta));$('change').style.color=delta<0?'#ffb2af':'#78edce';$('verdict').textContent=delta===0?'Try changing a proposed value.':delta>0?'Profit improves by this amount.':'Profit falls by this amount.';
 $('flow').innerHTML=`<div class="flow"><div><label>Proposed sales</label><div class="bar"></div><b>${money(b.revenue)}</b></div><span>−</span><div><label>Variable costs</label><div class="bar" style="background:#9eafc1"></div><b>${money(b.revenue-b.contribution)}</b></div><span>=</span><div><label>Contribution</label><div class="bar"></div><b>${money(b.contribution)}</b></div></div>`;
 $('totals').innerHTML=tableRow('Revenue',money(a.revenue),money(b.revenue))+tableRow('Variable costs',money(a.revenue-a.contribution),money(b.revenue-b.contribution))+tableRow('Contribution',money(a.contribution),money(b.contribution))+tableRow('Contribution ratio',percent(a.ratio),percent(b.ratio))+tableRow('All fixed costs',money(a.fixed),money(b.fixed))+tableRow('Operating profit',money(a.profit),money(b.profit),'profit')+tableRow('Break-even sales',money(a.breakEven),money(b.breakEven))+tableRow('Margin of safety',money(a.safety),money(b.safety));
 $('explain').textContent=`Your proposed sales leave ${money(b.contribution)} after variable costs. After ${money(b.fixed)} in fixed bills, you ${b.profit<0?'make a loss of':'have a profit of'} ${money(Math.abs(b.profit))}.`+(b.breakEven===null?' Break-even cannot be calculated with no sales or a non-positive contribution ratio.':'');
 $('products').innerHTML=b.products.map((p,i)=>{const q=a.products[i];const required=q.contribution<=0?'No positive contribution target':p.unitContribution>0?num(Math.ceil(q.contribution/p.unitContribution))+' units':'Not achievable at this price';if(!p.active&&!q.active&&p.retainedFixed===0&&q.retainedFixed===0)return '';return `<article><h3>${p.name}${p.active?'':' · stopped in proposal'}</h3><div class="table-wrap"><table><thead><tr><th>Measure</th><th>Current</th><th>Proposed</th></tr></thead><tbody>${tableRow('Revenue',money(q.revenue),money(p.revenue))}${tableRow('Variable costs',money(q.totalVariable),money(p.totalVariable))}${tableRow('Contribution per unit',money(q.unitContribution),money(p.unitContribution))}${tableRow('Total contribution',money(q.contribution),money(p.contribution))}${tableRow('Contribution ratio',percent(q.ratio),percent(p.ratio))}${tableRow('Retained product fixed costs',money(q.retainedFixed),money(p.retainedFixed))}${tableRow('Allocated shared costs',money(q.overhead),money(p.overhead))}${tableRow('Reported product profit',money(q.reported),money(p.reported))}${tableRow('Contribution per machine hour',money(q.perHour),money(p.perHour))}</tbody></table></div><p><b>Units needed to keep current contribution:</b> ${p.active?required:'Product is stopped.'}</p><p>Based on this product’s current contribution of ${money(q.contribution)}. Assumes enough demand and capacity.</p></article>`;}).join('');
 const ranked=b.products.filter(p=>p.active&&p.unitContribution>0).sort((x,y)=>y.perHour-x.perHour);$('capacity').textContent=`Proposed machine time: ${num(b.hours)} of ${num(state.proposed.capacity)} hours available. `+(b.hours>state.proposed.capacity?'This plan exceeds capacity. Reduce volume or allow for extra capacity costs. ':'The proposed volume fits within this capacity. ')+(ranked.length?`If hours become limited, ${ranked[0].name} contributes the most per hour (${money(ranked[0].perHour)}).`:'No active product has positive contribution.')+(b.unallocated?` Shared costs of ${money(b.unallocated)} remain at company level because there is no allocation base.`:'');}
document.addEventListener('input',e=>{const el=e.target;if(!el.dataset.key)return;if(el.type==='number'&&(!el.checkValidity()||el.value.trim()===''||!Number.isFinite(Number(el.value)))){el.setAttribute('aria-invalid','true');el.setAttribute('aria-describedby','invalid');$('invalid').textContent='Check this number. Use zero or more, whole units, and savings from 0 to 100%. Results show your last valid numbers.';return;}el.removeAttribute('aria-invalid');el.removeAttribute('aria-describedby');$('invalid').textContent=document.querySelector('[aria-invalid="true"]')?'Some inputs need correcting. Results use their last valid numbers.':'';const target=el.dataset.index==='company'?state[el.dataset.side]:state[el.dataset.side].products[Number(el.dataset.index)];target[el.dataset.key]=el.type==='checkbox'?el.checked:el.tagName==='SELECT'?el.value:Number(el.value);render();save();});

function renderLearning(a,b){
 const effects=[];
 b.products.forEach((p,i)=>{const q=a.products[i];const prefix=i===0?'bag':'pair of shoes';const price=(p.price-q.price)*q.units;const cost=-(p.variable-q.variable)*q.units;const volume=(p.units-q.units)*p.unitContribution;
 if(price)effects.push({value:price,text:'You '+(p.price>q.price?'raised':'cut')+' the '+prefix+' price by '+money(Math.abs(p.price-q.price))+' on the original '+num(q.units)+' units.'});
 if(cost)effects.push({value:cost,text:'The cost per '+prefix+' '+(p.variable>q.variable?'rose':'fell')+' by '+money(Math.abs(p.variable-q.variable))+' on the original '+num(q.units)+' units.'});
 if(volume)effects.push({value:volume,text:'You sell '+num(Math.abs(p.units-q.units))+' '+(p.units>q.units?'more':'fewer')+' '+(i===0?'bags':'pairs')+', each contributing '+money(p.unitContribution)+' at the proposed price and cost.'});});
 const fixed=a.fixed-b.fixed;if(fixed)effects.push({value:fixed,text:'Your total fixed bills '+(fixed>0?'fell':'rose')+' by '+money(Math.abs(fixed))+'.'});
 $('why').innerHTML=effects.length?'<h3>Why profit changes</h3><ul class="effects">'+effects.map(e=>'<li><p>'+e.text+'</p><strong class="'+(e.value<0?'negative':'positive')+'">'+(e.value>0?'+':'−')+money(Math.abs(e.value))+' profit</strong></li>').join('')+'</ul>':'<h3>Try a small change</h3><p>Change the proposed bag price from <b>€50 to €45</b>. Watch what happens to profit.</p>';
 $('simple-break').innerHTML=b.breakEven===null?'<p class="hint">Break-even is not available without a positive contribution ratio.</p>':'<div class="break-card"><span>Sales needed to cover your bills</span><strong>'+money(b.breakEven)+'</strong><p>This is your <b>break-even</b> point: zero profit.</p></div>';
 const extraCosts=state.current.products.some(p=>p.fixed>0)||state.proposed.products.some(p=>p.fixed>0);const activeExtra=state.current.products[1].active||state.proposed.products[1].active;const stopped=!state.current.products[0].active||!state.proposed.products[0].active;
 const flags=[extraCosts?'Extra product fixed costs are included.':'',activeExtra?'Shoes is included.':'',stopped?'Bags is stopped in at least one scenario.':''].filter(Boolean).join(' ');
 $('advanced-status').textContent=flags||'Optional: switch on Shoes to compare two products.';
 $('verdict').dataset.advanced=flags;
}
function comparison(label,a,b,format=money){return '<tr><th scope="row">'+label+'</th><td>'+format(a)+'</td><td>'+format(b)+'</td><td>'+(a===null||b===null?'—':b===a?'No change':(b>a?'+':'−')+format(Math.abs(b-a)))+'</td></tr>';}
const originalRender=render;
render=function(){originalRender();const a=calculate(state.current),b=calculate(state.proposed);$('totals').innerHTML=comparison('Revenue',a.revenue,b.revenue)+comparison('Variable costs',a.revenue-a.contribution,b.revenue-b.contribution)+comparison('Contribution',a.contribution,b.contribution)+comparison('Contribution ratio',a.ratio,b.ratio,n=>n===null?'No sales':num(n*100)+' pp')+comparison('All fixed costs',a.fixed,b.fixed)+comparison('Operating profit',a.profit,b.profit)+comparison('Break-even sales',a.breakEven,b.breakEven)+comparison('Margin of safety',a.safety,b.safety);const ratioRow=$('totals').rows[3];ratioRow.cells[1].textContent=percent(a.ratio);ratioRow.cells[2].textContent=percent(b.ratio);const flags=$('verdict').dataset.advanced;if(flags)$('verdict').textContent+=' '+flags;};

$('copy').onclick=()=>{state.proposed=structuredClone(state.current);drawInputs();render();save();$('invalid').textContent='';};$('reset').onclick=()=>{state={current:initial(),proposed:initial()};drawInputs();render();if(restoreMessage)$('save-status').textContent=restoreMessage;save();$('invalid').textContent='';};drawInputs();render();
