let state={current:initial(),proposed:initial()};
const money=n=>n===null?'Not available':new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);
const num=n=>new Intl.NumberFormat('en-IE',{maximumFractionDigits:2}).format(n);
const percent=n=>n===null?'No sales':num(n*100)+'%';
const $=id=>document.getElementById(id);
function row(label,key,index,opts={}){return `<div class="input-row"><span>${label}</span>${['current','proposed'].map(side=>{let value=index===null?state[side][key]:state[side].products[index][key];let attrs=`data-side="${side}" data-key="${key}" data-index="${index===null?'company':index}" aria-label="${side} ${index===null?'company':state[side].products[index].name} ${label}"`;if(opts.select)return `<select ${attrs}>${opts.select.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`;if(opts.check)return `<label class="check"><input type="checkbox" ${attrs} ${value?'checked':''}>Sell it</label>`;return `<input type="number" min="${opts.min||0}" ${opts.max?'max="'+opts.max+'"':''} step="${opts.step||'any'}" value="${value}" ${attrs}>`;}).join('')}</div>`;}
function drawInputs(){ $('inputs').innerHTML=state.current.products.map((p,i)=>`<h3 class="product-heading">${p.name}<span class="badge">Product ${i+1}</span></h3>${row('Sell this product','active',i,{check:true})}${row('Price per unit · €','price',i)}${row('Units sold','volume',i,{step:1})}${row('Variable cost per unit · €','variable',i)}<details><summary>Product fixed costs & machine time</summary>${row('Product fixed costs · €','fixed',i)}${row('Saved if stopped · %','avoidable',i,{max:100})}${row('Hours per unit','hours',i,{min:0.01})}<p class="hint">“Saved if stopped” is the share of this product’s fixed costs that really disappears. Uncheck “Sell it” to try stopping the product.</p></details>`).join('');$('company').innerHTML=row('Shared fixed costs · €','common',null)+row('Allocate shared costs by','allocation',null,{select:[['equal','Equal split'],['revenue','Revenue'],['units','Units sold']]})+row('Available machine hours','capacity',null);}
const tableRow=(label,a,b,cls='')=>`<tr class="${cls}"><td>${label}</td><td>${a}</td><td>${b}</td></tr>`;
function render(){const a=calculate(state.current),b=calculate(state.proposed);const delta=b.profit-a.profit;$('currentProfit').textContent=money(a.profit);$('proposedProfit').textContent=money(b.profit);$('change').textContent=delta===0?'No change':(delta>0?'+':'−')+money(Math.abs(delta));$('change').style.color=delta<0?'#ffb2af':'#78edce';$('verdict').textContent=delta===0?'Try changing a proposed value.':delta>0?'Profit improves by this amount.':'Profit falls by this amount.';
 $('flow').innerHTML=`<div class="flow"><div><label>Proposed sales</label><div class="bar"></div><b>${money(b.revenue)}</b></div><span>−</span><div><label>Variable costs</label><div class="bar" style="background:#9eafc1"></div><b>${money(b.revenue-b.contribution)}</b></div><span>=</span><div><label>Contribution</label><div class="bar"></div><b>${money(b.contribution)}</b></div></div>`;
 $('totals').innerHTML=tableRow('Revenue',money(a.revenue),money(b.revenue))+tableRow('Variable costs',money(a.revenue-a.contribution),money(b.revenue-b.contribution))+tableRow('Contribution',money(a.contribution),money(b.contribution))+tableRow('Contribution ratio',percent(a.ratio),percent(b.ratio))+tableRow('All fixed costs',money(a.fixed),money(b.fixed))+tableRow('Operating profit',money(a.profit),money(b.profit),'profit')+tableRow('Break-even sales',money(a.breakEven),money(b.breakEven))+tableRow('Margin of safety',money(a.safety),money(b.safety));
 $('explain').textContent=`Your proposed sales leave ${money(b.contribution)} after variable costs. After ${money(b.fixed)} in fixed bills, you ${b.profit<0?'make a loss of':'have a profit of'} ${money(Math.abs(b.profit))}.`+(b.breakEven===null?' Break-even cannot be calculated with no sales or a non-positive contribution ratio.':'');
 $('products').innerHTML=b.products.map((p,i)=>{const q=a.products[i];const required=q.contribution<=0?'No positive contribution target':p.unitContribution>0?num(Math.ceil(q.contribution/p.unitContribution))+' units':'Not achievable at this price';return `<article><h3>${p.name}${p.active?'':' · stopped in proposal'}</h3><div class="table-wrap"><table><thead><tr><th>Measure</th><th>Current</th><th>Proposed</th></tr></thead><tbody>${tableRow('Revenue',money(q.revenue),money(p.revenue))}${tableRow('Variable costs',money(q.totalVariable),money(p.totalVariable))}${tableRow('Contribution per unit',money(q.unitContribution),money(p.unitContribution))}${tableRow('Total contribution',money(q.contribution),money(p.contribution))}${tableRow('Contribution ratio',percent(q.ratio),percent(p.ratio))}${tableRow('Retained product fixed costs',money(q.retainedFixed),money(p.retainedFixed))}${tableRow('Allocated shared costs',money(q.overhead),money(p.overhead))}${tableRow('Reported product profit',money(q.reported),money(p.reported))}${tableRow('Contribution per machine hour',money(q.perHour),money(p.perHour))}</tbody></table></div><p><b>Units needed to keep current contribution:</b> ${p.active?required:'Product is stopped.'}</p><p>Based on this product’s current contribution of ${money(q.contribution)}. Assumes enough demand and capacity.</p></article>`;}).join('');
 const ranked=b.products.filter(p=>p.active&&p.unitContribution>0).sort((x,y)=>y.perHour-x.perHour);$('capacity').textContent=`Proposed machine time: ${num(b.hours)} of ${num(state.proposed.capacity)} hours available. `+(b.hours>state.proposed.capacity?'This plan exceeds capacity. Reduce volume or allow for extra capacity costs. ':'The proposed volume fits within this capacity. ')+(ranked.length?`If hours become limited, ${ranked[0].name} contributes the most per hour (${money(ranked[0].perHour)}).`:'No active product has positive contribution.')+(b.unallocated?` Shared costs of ${money(b.unallocated)} remain at company level because there is no allocation base.`:'');}
document.addEventListener('input',e=>{const el=e.target;if(!el.dataset.key)return;if(el.type==='number'&&(!el.checkValidity()||el.value.trim()===''||!Number.isFinite(Number(el.value)))){$('invalid').textContent='Enter a valid, non-negative number. Units must be whole numbers, hours per unit above zero, and savings from 0 to 100%. Results keep the last valid value.';return;}$('invalid').textContent='';const target=el.dataset.index==='company'?state[el.dataset.side]:state[el.dataset.side].products[Number(el.dataset.index)];target[el.dataset.key]=el.type==='checkbox'?el.checked:el.tagName==='SELECT'?el.value:Number(el.value);render();});
$('copy').onclick=()=>{state.proposed=structuredClone(state.current);drawInputs();render();$('invalid').textContent='';};$('reset').onclick=()=>{state={current:initial(),proposed:initial()};drawInputs();render();$('invalid').textContent='';};drawInputs();render();
